[eiko.package]
name = "eikobot-hyper-v"
version = "0.0.1"
description = ""
long_description = ""
long_description_content_type = "text/markdown"
author = "kazaamjt"
author_email = "kazaamjt@gmail.com"
license = "MIT"
source_dir = "hyper_v"
eikobot_requires = ">=0.6.0"
requires = []
python_requires = []
